#!/data/data/com.termux/files/usr/bin/bash
# Project name : Fam-Hacker_Client
# Coded by: tthatgguy1 (You dont become a coder by just changing the credits)
# Github: https://github.com/tthatgguy1/Fam-Hacker_Client
# Date : 12/04/2024
# Updated 09/01/2025

##----------------------------------------------------------##
##==========================================================##
##《■■■■■■■■■■■■■■■■■■■-Color-Setup-■■■■■■■■■■■■■■■■■■■■■■》##
##==========================================================##
##----------------------------------------------------------##
ESC=$'\e'                       # ${ESC} $ESC

BLK="${ESC}[38;2;0;0;0m"        # ${BLK}   $BLK - Black
GRN="${ESC}[38;2;51;255;0m"     # ${GRN}   $GRN - Lime Green
PNK="${ESC}[38;2;255;16;240m"   # ${PNK}   $PNK - Bright Magenta
BLU="${ESC}[38;2;0;102;255m"    # ${BLU}   $BLU - Medium Blue
MDB="${ESC}[38;2;25;25;112m"    # ${MDB}   $MDB - Midnight Blue
GRY="${ESC}[38;2;208;208;208m"  # ${GRY}   $GRY - Gray

BONG="${ESC}[38;2;255;140;0m"   # ${BONG}  $BONG - Pumpkin Orange
BBLK="${ESC}[38;2;128;128;128m" # ${BBLK}  $BBLK - Bright Black
NYLW="${ESC}[38;2;255;255;0m"   # ${NYLW}  $NYLW - Neon Yellow
BYLW="${ESC}[38;2;255;255;51m"  # ${BYLW}  $BYLW - Bright Yellow
BCYN="${ESC}[38;2;0;255;255m"   # ${BCYN}  $BCYN - Cyan
BGRN="${ESC}[38;2;0;255;0m"     # ${BGRN}  $BGRN - Bright Green
ACID="${ESC}[38;2;204;255;0m"   # ${ACID}  $ACID - Acid Green
IBLU="${ESC}[32;2;75;0;130m"    # ${IBLU}  $IBLU - Indigo Blue
NPPL="${ESC}[38;2;188;19;254m"  # ${NPPL}  $NPPL - Neon Purple
BWHT="${ESC}[38;2;255;255;255m" # ${BWHT}  #BWHT - Bright White
RESET="${ESC}[0m"               # ${RESET} $RESET

OUT_BASE="$HOME/storage/shared/Fam-Hacker-Pit-Kit/Fam-Hacker-Torrent-Pit"
LOG_DIR="$HOME/storage/shared/Fam-Hacker-Pit-Kit/.cache/Aria2c_Logs"
mkdir -p "$OUT_BASE" "$LOG_DIR"

TERMUX_DOWN="/data/data/com.termux/files/home/downloads"
TORPIT="/data/data/com.termux/files/home/storage/shared/0Nah-Fam-Torrent-Kit/Fam-Hacker-Torrent-Pit"

GREAT_COOKING="mpv $HOME/storage/shared/0Nah-Fam-Torrent-Kit/.NFS-Data/sfx/Cooking_Great.mp3"
SECRET_SOUND="mpv $HOME/storage/shared/0Nah-Fam-Torrent-Kit/.NFS-Data/sfx/Secret_Sound.mp3"
TP_HEART="mpv $HOME/storage/shared/0Nah-Fam-Torrent-Kit/.NFS-Data/sfx/TLOZ-WW_Heart_Container.mp3"
MMF="mpv $HOME/storage/shared/0Nah-Fam-Torrent-Kit/.NFS-Data/sfx/MMF.mp3"

## Torrent Logo & Date
echo '
─███████╗╔█████╗─███╗───███╗─██╗──██╗╔█████╗─╔██████╗██╗──██╗██████╗─
─██╔════╝██╔══██╗████╗─████║─██║──██║██╔══██╗██╔════╝██║─██╔╝██╔══██╗
─█████╗──███████║██╔████╔██║─███████║███████║██║─────█████╔╝─██████╔╝
─██╔══╝──██╔══██║██║╚██╔╝██║─██╔══██║██╔══██║██║─────██╔═██╗─██╔══██╗
─██║─────██║──██║██║─╚═╝─██║─██║──██║██║──██║╚██████╗██║──██╗██║──██║
─╚═╝─────╚═╝──╚═╝╚═╝─────╚═╝─╚═╝──╚═╝╚═╝──╚═╝─╚═════╝╚═╝──╚═╝╚═╝──╚═╝
───████████╗╔██████╗─██████╗─██████╗─███████╗███╗───██╗████████╗─────
───╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗──██║╚══██╔══╝─────
──────██║───██║───██║██████╔╝██████╔╝█████╗──██╔██╗─██║───██║────────
──────██║───██║───██║██╔══██╗██╔══██╗██╔══╝──██║╚██╗██║───██║────────
──────██║───╚██████╔╝██║──██║██║──██║███████╗██║─╚████║───██║────────
──────╚═╝────╚═════╝─╚═╝──╚═╝╚═╝──╚═╝╚══════╝╚═╝──╚═══╝───╚═╝────────
──────────╔██████╗██╗─────██╗███████╗███╗───██╗████████╗─────────────
──────────██╔════╝██║─────██║██╔════╝████╗──██║╚══██╔══╝─────────────
──────────██║─────██║─────██║█████╗──██╔██╗─██║───██║────────────────
──────────██║─────██║─────██║██╔══╝──██║╚██╗██║───██║────────────────
──────────╚██████╗███████╗██║███████╗██║─╚████║───██║────────────────
───────────╚═════╝╚══════╝╚═╝╚══════╝╚═╝──╚═══╝───╚═╝────────────────
---------------------------[Nah-Fam_Studios]------------------------------' | lolcat

##----------------------------------------------------------##
printf "\n"
  date +"%l:%M:%S %p" | lolcat --animate -d 15
printf "\n"

## File Info
  cd downloads
    newf=$(ls -Art | tail -n1)
    printf "\n"
    cowsay -r "${newf}" | lolcat
  printf "\n"

## Aria2 Download
LOG_FILE="$LOG_DIR/nfs-file-editor_$(date +%Y%m%d-%H%M%S).log"
  printf "\n"
    printf "To Quit, Press ctrl + c Together And Press Enter\n"
    printf "\n"
    ${GREAT_COOKING} > /dev/null 2&>1
  printf "\n"

aria2c \
  -d "${TORPIT}" "${TERMUX_DOWN}/${newf}" \
  --max-connection-per-server=16 \
  --seed-time=0 \
  --summary-interval=0 \
  --console-log-level=warn \
  --show-console-readout=true \
  --log-level=notice 2>>"$LOG_FILE"

## Sound 2
  printf "\n"
    ${MMF} >/dev/null 2>&1
  ${TP_HEART} >/dev/null 2&>1
sleep 1.0

## Termux Move
  printf '\n'
    sleep 2.0
    printf "Press Any Button To Continue."
    read -p
  printf "\n"
clear

## Move Completed File
  echo "${PNK}"
    printf "\n"
    printf "Fam-Hacker_Client Is Ready To Move The Completed Download\n"
    read -p ">"
  printf "\n"
clear
  printf "\n"
shopt -s extglob
## --- Moves Completed Download To Mother Folder --- ##
  mv "$(ls -t -- * | head -n1)" "${TORPIT}"
    printf "\n"
    printf "The Completed Download Has Been Moved Successfully\n" | lolcat --animate -d 75
  ${SECRET_SOUND} > /dev/null 2>&1
sleep 1.0

## Removing Files in /data/data/com.termux/files/home/downloads
  echo "${ACID}"
    rm -rf ${TERMUX_DOWN}/* > /dev/null 2&>1
    printf "Press Any Key To Quit The Program"
    read -p ">"
  printf "\n"
sleep 4.0

